name = "soundscape"
main = "worker/main.ts"
compatibility_date = "2026-02-12"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true
workers_dev = false

[observability]
enabled = true
head_sampling_rate = 1

[[routes]]
pattern = "sound.ct2.io"
custom_domain = true

[[d1_databases]]
binding = "INFO_STORE"
database_name = "soundscape"
database_id = "5b7c43cc-faf9-4bb1-872b-ef4de18009ae"

[[r2_buckets]]
binding = "OBJECT_STORE"
bucket_name = "soundscape"
